let str = ("Hello");
let str1 = ("owu");
let str2 = ('com');
let str3 = (`ua`);
let n1 = 1;
let n2 = 10;
let n3 = -999;
let n4 = 123;
let n5 = 3.14;
let n6 = 2.7;
let n7 = 16;
let bool1 = true;
let bool2 = false;
console.log (n1);
console.log (n2);
console.log (n3);
console.log (n4);
console.log (n5);
console.log (n6);
console.log (n7);
alert(`${str} ${str1} ${str2} ${str3}`);
document.write(bool1);
document.write(" \n" + bool2);
let firstName = ("Mariia");
let middleName = ("Dmytrivna");
let lastName = ("Velykotska");
let sp =(" ");
let Name = lastName +sp + firstName + sp + middleName;
console.log (Name);

let a= 100;
let b= '100';
let c = true;
console.log (typeof a);
console.log (typeof b);
console.log (typeof c);
let name = prompt("Your first name?"," " );
let surname = prompt("Your last name?", " " );
let age = prompt("Your age?", " " );
let fullname = name + sp + surname + sp + age;
console.log (fullname);